name: "Test Suite"
on:
  push:
  pull_request:

jobs:
  formatting:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Ensure rustfmt is installed and setup problem matcher
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - run: echo "cargohome=${CARGO_HOME:-$HOME/.cargo}/bin" >> $GITHUB_OUTPUT
        shell: bash
        id: cargo-home
      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            ${{ steps.cargo-home.outputs.cargohome }}/.crates.toml
            ${{ steps.cargo-home.outputs.cargohome }}/.crates2.json
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@add-manifest-path
        with:
          manifest-path: ./proj/Cargo.toml
